export default {
    GET_USERS: {
        FETCH: 'GET_USERS_FETCH',
        SUCCESS: 'GET_USERS_SUCCESS',
        ERROR: 'GET_USERS_ERROR',
    },
    CREATE_USER: {
        FETCH: 'CREATE_USER_FETCH',
        SUCCESS: 'CREATE_USER_SUCCSESS',
        ERROR: 'CREATE_USER_ERROR',
        MODAL_FORM: {
            OPEN: 'CREATE_USER_MODAL_FORM_OPEN',
            CLOSE: 'CREATE_USER_MODAL_FORM_CLOSE',
        },
    },
    UPDATE_USER: {
        FETCH: 'UPDATE_USER_FETCH',
        SUCCESS: 'UPDATE_USER_SUCCSESS',
        ERROR: 'UPDATE_USER_ERROR',
    },
    UPDATE_USER_IN_STORE: {
        FETCH: 'UPDATE_USER_IN_STORE_FETCH',
        SUCCESS: 'UPDATE_USER_IN_STORE_SUCCSESS',
        ERROR: 'UPDATE_USER__IN_STORE_ERROR',
    },
    DELETE_USER: {
        FETCH: 'DELETE_USER_FETCH',
        SUCCESS: 'DELETE_USER_SUCCSESS',
        ERROR: 'DELETE_USER_ERROR',
    },
    DELETE_USER_IN_STORE: {
        FETCH: 'DELETE_USER_IN_STORE_FETCH',
        SUCCESS: 'DELETE_USER_IN_STORE_SUCCSESS',
    },
};
